controller_manager:
  ros__parameters:
    update_rate: 50
    use_sim_time: true

    broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    controller:
      type: diff_drive_controller/DiffDriveController


controller:
  ros__parameters:
    left_wheel_names: ["left_joint"]
    right_wheel_names: ["right_joint"]
    wheel_separation: 0.3
    wheel_radius: 0.1
    use_stamped_vel: false
    publish_rate: 50.0
    enable_odom_tf: true
    open_loop: false