joy_teleop:
  ros__parameters:
    move:
      type: topic
      interface_type: geometry_msgs/msg/Twist
      topic_name: /controller/cmd_vel_unstamped
      deadman_buttons: [5]
      axis_mappings:
        linear-x:
          axis: 7
          scale: -1.0
          offset: 0.0

        angular-z:
          axis: 6
          scale: 1.0
          offset: 0.0
